spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/test?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qW110110110@
    #静态页面的配置
  thymeleaf:
    encoding: UTF-8
    cache: false
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
# 文件上传的最大限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  resources:
#    static-locations: classpath:/static/,classpath/templates/